name: "Push containers to Docker Hub on release"

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        run: cp .env.example .env

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the backend container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./prod.Dockerfile
          target: backend
          push: true
          platforms: |
            linux/amd64
          tags: |
            ghcr.io/synapto-platform/hoppscotch-backend:latest
            ghcr.io/synapto-platform/hoppscotch-backend:${{ github.ref_name }}

      - name: Build and push the frontend container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./prod.Dockerfile
          target: app
          push: true
          platforms: |
            linux/amd64
          tags: |
            ghcr.io/synapto-platform/hoppscotch-frontend:latest
            ghcr.io/synapto-platform/hoppscotch-frontend:${{ github.ref_name }}

      - name: Build and push the admin dashboard container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./prod.Dockerfile
          target: sh_admin
          push: true
          platforms: |
            linux/amd64
          tags: |
            ghcr.io/synapto-platform/hoppscotch-admin:latest
            ghcr.io/synapto-platform/hoppscotch-admin:${{ github.ref_name }}
